import ImageGalleryComponent from '@podenco/components/imageGallery';
import SearchActionsComponent from '@podenco/components/searchActions';
import useImageList from '@podenco/hooks/useImageList';
import useInitSearchPage from '@podenco/hooks/useInitSearchPage';
import useQueryParams from '@podenco/hooks/useQueryParams';
import styles from '@podenco/styles/Home.module.css';
import Head from 'next/head';

export default function Home() {
  useQueryParams();

  useInitSearchPage();

  const data = useImageList();

  return (
    <>
      <Head>
        <title>Image Editor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <ImageGalleryComponent data={data} />
        <SearchActionsComponent />
      </main>
    </>
  );
}
