import ImageGalleryComponent, { APIImage } from '@podenco/components/imageGallery';
import SearchActionsComponent from '@podenco/components/searchActions';
import useImageList from '@podenco/hooks/useImageList';
import useQueryParams from '@podenco/hooks/useQueryParams';
import styles from '@podenco/styles/Home.module.css';
import Head from 'next/head';
import { useState } from 'react';

export default function Home() {
  const [data, setData] = useState<APIImage[] | null>(null);
  const [params, setParams] = useQueryParams();

  const { page } = params;

  useImageList({ page, setData, setParams, data });

  return (
    <>
      <Head>
        <title>Image Editor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <ImageGalleryComponent data={data} />
        <SearchActionsComponent page={page} setParams={setParams} />
      </main>
    </>
  );
}
